version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[dependabot] "
    groups:
      actions:
        update-types:
          - "major"
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[dependabot] "
    groups:
      docs:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[dependabot] "
    groups:
      major-versions:
        update-types:
          - "major"
      minor-versions:
        update-types:
          - "minor"
          - "patch"
