/***********************************************************************
 * Copyright (c) 2013-2025 General Atomics Integrated Intelligence, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution and is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 ***********************************************************************/

package org.locationtech.geomesa.trino.spatial.iceberg.transforms;

import org.apache.iceberg.PartitionSpec;
import org.apache.iceberg.PartitionSpecParser;
import org.apache.iceberg.Schema;
import org.apache.iceberg.transforms.Transform;
import org.apache.iceberg.transforms.Transforms;
import org.apache.iceberg.transforms.UnknownTransform;
import org.apache.iceberg.types.Types;
import org.junit.jupiter.api.Test;
import org.locationtech.geomesa.trino.spatial.iceberg.GeometryType;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.Envelope;
import org.locationtech.jts.geom.GeometryFactory;
import org.locationtech.jts.geom.Point;
import org.locationtech.jts.geom.Polygon;
import org.locationtech.jts.io.WKBWriter;

import java.nio.ByteBuffer;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Behavioral tests for {@link Z2Transform}. After delegating to upstream
 * {@link SfcBridge}, the stored values are bit-for-bit identical to GeoMesa's
 * {@code Z2SFC.index} (31 bits/axis, 62-bit non-negative). The cross-language
 * parity corpus at {@code tools/tests/data/z2_parity_corpus.json} (regenerated by
 * {@code Z2ParityCorpusGenerator}) is the ground-truth byte-exact reference;
 * these tests assert behavioral invariants only.
 */
class Z2TransformTest {

    private static final GeometryFactory GF = new GeometryFactory();
    private static final long Z2_MAX_62 = (1L << 62) - 1L;

    private static ByteBuffer wkb(double lon, double lat) {
        Point p = GF.createPoint(new Coordinate(lon, lat));
        return ByteBuffer.wrap(new WKBWriter().write(p));
    }

    @Test
    void canTransformBinaryAndGeometryNotString() {
        Z2Transform t = Z2Transform.of(18);
        assertThat(t.canTransform(Types.BinaryType.get())).isTrue();
        assertThat(t.canTransform(GeometryType.get())).isTrue();
        assertThat(t.canTransform(Types.StringType.get())).isFalse();
    }

    @Test
    void resultTypeIsLong() {
        assertThat(Z2Transform.of(18).getResultType(GeometryType.get()))
            .isEqualTo(Types.LongType.get());
    }

    @Test
    void applyMatchesSfcBridge() {
        long expected = SfcBridge.z2Index(-77.0, 38.9);
        assertThat(Z2Transform.of(18).apply(wkb(-77.0, 38.9))).isEqualTo(expected);
    }

    @Test
    void applyAtSouthwestCornerIsZero() {
        assertThat(Z2Transform.of(18).apply(wkb(-180.0, -90.0))).isZero();
    }

    @Test
    void applyReturnsNullForEmptyGeometry() {
        byte[] emptyPolygon = new WKBWriter().write(GF.createPolygon());
        assertThat(Z2Transform.of(18).apply(ByteBuffer.wrap(emptyPolygon))).isNull();
    }

    @Test
    void applyRejectsExtendedGeometries() {
        // point-only: centroid-indexing extents breaks query-side pruning
        Polygon poly = GF.createPolygon(new Coordinate[]{
            new Coordinate(-80, 35), new Coordinate(-70, 35),
            new Coordinate(-70, 45), new Coordinate(-80, 45),
            new Coordinate(-80, 35)});
        ByteBuffer wkb = ByteBuffer.wrap(new WKBWriter().write(poly));
        assertThatThrownBy(() -> Z2Transform.of(18).apply(wkb))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessageContaining("Point")
            .hasMessageContaining("xz2");
    }

    @Test
    void applyClampsCoordinatesSlightlyOutsideWgs84Bounds() {
        Z2Transform t = Z2Transform.of(18);
        assertThat(t.apply(wkb(180.0000001, 39.0))).isEqualTo(SfcBridge.z2Index(180.0, 39.0));
        assertThat(t.apply(wkb(-180.0000001, 39.0))).isEqualTo(SfcBridge.z2Index(-180.0, 39.0));
        assertThat(t.apply(wkb(116.0, 90.0000001))).isEqualTo(SfcBridge.z2Index(116.0, 90.0));
        assertThat(t.apply(wkb(116.0, -90.0000001))).isEqualTo(SfcBridge.z2Index(116.0, -90.0));
    }

    @Test
    void rangesClampQueryEnvelopeOutsideWgs84Bounds() {
        // e.g. a DWITHIN buffer near a pole exceeds the WGS84 bounds
        List<String[]> clamped = Z2Transform.z2RangesAtReferenceHex(
            new Envelope(-180.0, -179.0, 88.0, 90.0), 16);
        List<String[]> outside = Z2Transform.z2RangesAtReferenceHex(
            new Envelope(-180.5, -179.0, 88.0, 90.5), 16);
        assertThat(outside).usingRecursiveComparison().isEqualTo(clamped);
    }

    @Test
    void applyAtNortheastCornerIsMax62Bits() {
        assertThat(Z2Transform.of(18).apply(wkb(180.0, 90.0))).isEqualTo(Z2_MAX_62);
    }

    @Test
    void applyOriginIsNearHalfMax() {
        // Z2SFC.index(0, 0) at 31-bit precision lands at the bit pattern
        // where both nx and ny equal 2^30 (the half-grid boundary). The exact
        // value is deterministic — assert the high-level invariant that it's
        // strictly between zero and the 62-bit max.
        long z = Z2Transform.of(18).apply(wkb(0.0, 0.0));
        assertThat(z).isGreaterThan(0L).isLessThan(Z2_MAX_62);
    }

    @Test
    void applyOutputsAreNonNegativeAnd62BitBounded() {
        double[] lons = {-179.999, -77.0, 0.0, 139.7, 179.999};
        double[] lats = { -89.999,  38.9, 0.0,  35.7,  89.999};
        for (double lon : lons) {
            for (double lat : lats) {
                long z = Z2Transform.of(18).apply(wkb(lon, lat));
                assertThat(z).isBetween(0L, Z2_MAX_62);
            }
        }
    }

    @Test
    void distantPointsProduceDifferentValues() {
        long a = Z2Transform.of(18).apply(wkb(-77.0, 38.9));
        long b = Z2Transform.of(18).apply(wkb(139.7, 35.7));
        assertThat(a).isNotEqualTo(b);
    }

    @Test
    void indexOfMatchesApplyForPointCentroid() {
        Z2Transform t = Z2Transform.of(18);
        assertThat(t.indexOf(-77.0, 38.9)).isEqualTo(t.apply(wkb(-77.0, 38.9)));
    }

    @Test
    void applyReturnsNullForNullInput() {
        assertThat(Z2Transform.of(18).apply(null)).isNull();
    }

    @Test
    void invalidWkbThrows() {
        assertThatThrownBy(() -> Z2Transform.of(18).apply(ByteBuffer.wrap(new byte[]{0, 1, 2})))
            .isInstanceOf(RuntimeException.class);
    }

    @Test
    void bitsValidationRejectsInvalidValues() {
        assertThatThrownBy(() -> Z2Transform.of(0)).isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> Z2Transform.of(-2)).isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> Z2Transform.of(13)).isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> Z2Transform.of(66)).isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void bitsAccessorReturnsConstructorArg() {
        assertThat(Z2Transform.of(18).bits()).isEqualTo(18);
        assertThat(Z2Transform.of(64).bits()).isEqualTo(64);
    }

    @Test
    void toStringFormat() {
        assertThat(Z2Transform.of(18).toString()).isEqualTo("z2[18]");
        assertThat(Z2Transform.of(8).toString()).isEqualTo("z2[8]");
    }

    @Test
    void equalsAndHashCode() {
        assertThat(Z2Transform.of(18)).isEqualTo(Z2Transform.of(18));
        assertThat(Z2Transform.of(18).hashCode()).isEqualTo(Z2Transform.of(18).hashCode());
        assertThat(Z2Transform.of(18)).isNotEqualTo(Z2Transform.of(20));
    }

    // ── hexEncode (unsigned 16-char hex) ─────────────────────────────────

    @Test
    void hexEncodeProduces16CharLowercaseHex() {
        String h = Z2Transform.encodeColumn(SfcBridge.z2Index(-77.0, 38.9));
        assertThat(h).hasSize(16);
        assertThat(h).doesNotMatch(".*[A-F].*");
        assertThat(h).doesNotStartWith("-");
    }

    @Test
    void hexEncodeExtremes() {
        // Z2SFC outputs are non-negative 62-bit Longs; the top 2 bits are
        // always zero, so unsigned-hex values start with one of 0, 1, 2, 3.
        assertThat(Z2Transform.hexEncode(0L)).isEqualTo("0000000000000000");
        assertThat(Z2Transform.hexEncode(Z2_MAX_62)).isEqualTo("3fffffffffffffff");
    }

    @Test
    void hexEncodeOrderingMatchesNumericOrdering() {
        long[] values = {0L, 1L, 1L << 30, 1L << 60, Z2_MAX_62};
        for (int i = 0; i < values.length - 1; i++) {
            String lo = Z2Transform.hexEncode(values[i]);
            String hi = Z2Transform.hexEncode(values[i + 1]);
            assertThat(lo.compareTo(hi))
                .as("hex(%d) must compare less than hex(%d)", values[i], values[i + 1])
                .isNegative();
        }
    }

    // ── Range pushdown ────────────────────────────────────────────────────

    @Test
    void nearWorldEnvelopeRangeCountIsCappedButStillCoversPoints() {
        Envelope env = new Envelope(-179.9, 179.9, -89.9, 89.9);
        List<String[]> ranges = Z2Transform.z2RangesAtReferenceHex(env, 20);
        assertThat(ranges).isNotEmpty();
        assertThat(ranges.size()).isLessThanOrEqualTo(Z2Transform.MAX_RANGES * 2);
        for (double[] pt : new double[][] {{0.5, 0.5}, {-122.4, 37.8}, {151.2, -33.9}}) {
            String stored = Z2Transform.encodeColumn(SfcBridge.z2Index(pt[0], pt[1]));
            assertThat(ranges.stream()
                .anyMatch(r -> r[0].compareTo(stored) <= 0 && stored.compareTo(r[1]) <= 0))
                .as("point (%s, %s) still covered by capped ranges", pt[0], pt[1])
                .isTrue();
        }
    }

    @Test
    void z2RangesAtReferenceHexValidatesPartitionBits() {
        Envelope env = new Envelope(0.0, 1.0, 0.0, 1.0);
        assertThatThrownBy(() -> Z2Transform.z2RangesAtReferenceHex(env, 0))
            .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> Z2Transform.z2RangesAtReferenceHex(env, 13))
            .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> Z2Transform.z2RangesAtReferenceHex(env, 66))
            .isInstanceOf(IllegalArgumentException.class);
    }

    @Test
    void z2RangesAtReferenceHexEndpointsAre16CharLowercase() {
        Envelope env = new Envelope(-80.0, -70.0, 35.0, 45.0);
        List<String[]> ranges = Z2Transform.z2RangesAtReferenceHex(env, 20);
        assertThat(ranges).isNotEmpty();
        for (String[] r : ranges) {
            assertThat(r).hasSize(2);
            assertThat(r[0]).hasSize(16).doesNotMatch(".*[A-F].*").doesNotStartWith("-");
            assertThat(r[1]).hasSize(16).doesNotMatch(".*[A-F].*").doesNotStartWith("-");
        }
    }

    @Test
    void z2RangesAtReferenceHexEndpointsLowerLessOrEqualUpper() {
        Envelope env = new Envelope(-80.0, -70.0, 35.0, 45.0);
        List<String[]> ranges = Z2Transform.z2RangesAtReferenceHex(env, 20);
        for (String[] r : ranges) {
            assertThat(r[0].compareTo(r[1])).isLessThanOrEqualTo(0);
        }
    }

    @Test
    void z2RangesCoverLexEncodedAppliedValueForPointInEnvelope() {
        // For a point inside the query envelope, its stored lex-encoded Z2
        // must fall within at least one returned range. This is the
        // pushdown-correctness invariant.
        Envelope env = new Envelope(-80.0, -70.0, 35.0, 45.0);
        double[][] points = {
            {-75.0, 40.0}, {-79.0, 36.0}, {-71.0, 44.0}, {-77.0, 38.9}
        };
        List<String[]> ranges = Z2Transform.z2RangesAtReferenceHex(env, 20);
        for (double[] p : points) {
            String stored = Z2Transform.encodeColumn(SfcBridge.z2Index(p[0], p[1]));
            boolean covered = ranges.stream().anyMatch(r ->
                stored.compareTo(r[0]) >= 0 && stored.compareTo(r[1]) <= 0);
            assertThat(covered)
                .as("lex-encoded Z2 %s for point (%s, %s) not covered by ranges %s",
                    stored, p[0], p[1], ranges)
                .isTrue();
        }
    }

    /**
     * Z2Transform is intentionally NOT a registerable Iceberg partition
     * transform — Iceberg's metadata round-trip recognizes only the built-in
     * transforms, and {@link Transforms#fromString(String)} returns
     * {@link UnknownTransform} for any unknown encoding. We rely instead on
     * the truncate-string scheme over a VARCHAR partition column. This test
     * documents the design constraint and fails if Iceberg ever opens an SPI
     * for custom transforms.
     */
    @Test
    void z2TransformCannotBePluggedIntoIcebergPartitioning() {
        Transform<?, ?> direct = Transforms.fromString("z2[8]");
        assertThat(direct).isInstanceOf(UnknownTransform.class);

        @SuppressWarnings("unchecked")
        Transform<ByteBuffer, Long> typed = (Transform<ByteBuffer, Long>) direct;
        assertThatThrownBy(() -> typed.apply(wkb(-77.0, 38.9)))
            .isInstanceOf(UnsupportedOperationException.class);

        Schema schema = new Schema(Types.NestedField.required(1, "geom", Types.BinaryType.get()));
        String json = "{\"spec-id\":0,\"fields\":[{"
            + "\"name\":\"geom_z2_part\","
            + "\"transform\":\"z2[8]\","
            + "\"source-id\":1,"
            + "\"field-id\":1000"
            + "}]}";
        PartitionSpec parsed = PartitionSpecParser.fromJson(schema, json);
        assertThat(parsed.fields().get(0).transform()).isInstanceOf(UnknownTransform.class);

        boolean hasPublicCustomAdd = java.util.Arrays.stream(
                org.apache.iceberg.PartitionSpec.Builder.class.getDeclaredMethods())
            .filter(m -> "add".equals(m.getName()))
            .filter(m -> {
                Class<?>[] p = m.getParameterTypes();
                return p.length == 3
                    && p[0] == int.class
                    && p[1] == String.class
                    && org.apache.iceberg.transforms.Transform.class.isAssignableFrom(p[2]);
            })
            .anyMatch(m -> java.lang.reflect.Modifier.isPublic(m.getModifiers()));
        assertThat(hasPublicCustomAdd).isFalse();
    }
}
