// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KryoLazyDensityProtoGenerator.proto

package org.locationtech.geomesa.hbase.proto;

public final class KryoLazyDensityProto {
  private KryoLazyDensityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DensityRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DensityRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes byteFilter = 1;</code>
     */
    boolean hasByteFilter();
    /**
     * <code>required bytes byteFilter = 1;</code>
     */
    com.google.protobuf.ByteString getByteFilter();
  }
  /**
   * Protobuf type {@code DensityRequest}
   */
  public static final class DensityRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DensityRequest)
      DensityRequestOrBuilder {
    // Use DensityRequest.newBuilder() to construct.
    private DensityRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DensityRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DensityRequest defaultInstance;
    public static DensityRequest getDefaultInstance() {
      return defaultInstance;
    }

    public DensityRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DensityRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              byteFilter_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.class, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<DensityRequest> PARSER =
        new com.google.protobuf.AbstractParser<DensityRequest>() {
      public DensityRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DensityRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DensityRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BYTEFILTER_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString byteFilter_;
    /**
     * <code>required bytes byteFilter = 1;</code>
     */
    public boolean hasByteFilter() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes byteFilter = 1;</code>
     */
    public com.google.protobuf.ByteString getByteFilter() {
      return byteFilter_;
    }

    private void initFields() {
      byteFilter_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasByteFilter()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, byteFilter_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, byteFilter_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest)) {
        return super.equals(obj);
      }
      org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest other = (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest) obj;

      boolean result = true;
      result = result && (hasByteFilter() == other.hasByteFilter());
      if (hasByteFilter()) {
        result = result && getByteFilter()
            .equals(other.getByteFilter());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasByteFilter()) {
        hash = (37 * hash) + BYTEFILTER_FIELD_NUMBER;
        hash = (53 * hash) + getByteFilter().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DensityRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DensityRequest)
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.class, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.Builder.class);
      }

      // Construct using org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        byteFilter_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityRequest_descriptor;
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest getDefaultInstanceForType() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.getDefaultInstance();
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest build() {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest buildPartial() {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest result = new org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.byteFilter_ = byteFilter_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest) {
          return mergeFrom((org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest other) {
        if (other == org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.getDefaultInstance()) return this;
        if (other.hasByteFilter()) {
          setByteFilter(other.getByteFilter());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasByteFilter()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString byteFilter_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes byteFilter = 1;</code>
       */
      public boolean hasByteFilter() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes byteFilter = 1;</code>
       */
      public com.google.protobuf.ByteString getByteFilter() {
        return byteFilter_;
      }
      /**
       * <code>required bytes byteFilter = 1;</code>
       */
      public Builder setByteFilter(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        byteFilter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes byteFilter = 1;</code>
       */
      public Builder clearByteFilter() {
        bitField0_ = (bitField0_ & ~0x00000001);
        byteFilter_ = getDefaultInstance().getByteFilter();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DensityRequest)
    }

    static {
      defaultInstance = new DensityRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DensityRequest)
  }

  public interface DensityResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DensityResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Pair pairs = 1;</code>
     */
    java.util.List<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair> 
        getPairsList();
    /**
     * <code>repeated .Pair pairs = 1;</code>
     */
    org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair getPairs(int index);
    /**
     * <code>repeated .Pair pairs = 1;</code>
     */
    int getPairsCount();
    /**
     * <code>repeated .Pair pairs = 1;</code>
     */
    java.util.List<? extends org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.PairOrBuilder> 
        getPairsOrBuilderList();
    /**
     * <code>repeated .Pair pairs = 1;</code>
     */
    org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.PairOrBuilder getPairsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DensityResponse}
   */
  public static final class DensityResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DensityResponse)
      DensityResponseOrBuilder {
    // Use DensityResponse.newBuilder() to construct.
    private DensityResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DensityResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DensityResponse defaultInstance;
    public static DensityResponse getDefaultInstance() {
      return defaultInstance;
    }

    public DensityResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DensityResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                pairs_ = new java.util.ArrayList<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair>();
                mutable_bitField0_ |= 0x00000001;
              }
              pairs_.add(input.readMessage(org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          pairs_ = java.util.Collections.unmodifiableList(pairs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.class, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<DensityResponse> PARSER =
        new com.google.protobuf.AbstractParser<DensityResponse>() {
      public DensityResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DensityResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DensityResponse> getParserForType() {
      return PARSER;
    }

    public static final int PAIRS_FIELD_NUMBER = 1;
    private java.util.List<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair> pairs_;
    /**
     * <code>repeated .Pair pairs = 1;</code>
     */
    public java.util.List<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair> getPairsList() {
      return pairs_;
    }
    /**
     * <code>repeated .Pair pairs = 1;</code>
     */
    public java.util.List<? extends org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.PairOrBuilder> 
        getPairsOrBuilderList() {
      return pairs_;
    }
    /**
     * <code>repeated .Pair pairs = 1;</code>
     */
    public int getPairsCount() {
      return pairs_.size();
    }
    /**
     * <code>repeated .Pair pairs = 1;</code>
     */
    public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair getPairs(int index) {
      return pairs_.get(index);
    }
    /**
     * <code>repeated .Pair pairs = 1;</code>
     */
    public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.PairOrBuilder getPairsOrBuilder(
        int index) {
      return pairs_.get(index);
    }

    private void initFields() {
      pairs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < pairs_.size(); i++) {
        output.writeMessage(1, pairs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < pairs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pairs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse)) {
        return super.equals(obj);
      }
      org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse other = (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse) obj;

      boolean result = true;
      result = result && getPairsList()
          .equals(other.getPairsList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getPairsCount() > 0) {
        hash = (37 * hash) + PAIRS_FIELD_NUMBER;
        hash = (53 * hash) + getPairsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DensityResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DensityResponse)
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.class, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.Builder.class);
      }

      // Construct using org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPairsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (pairsBuilder_ == null) {
          pairs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pairsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityResponse_descriptor;
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse getDefaultInstanceForType() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance();
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse build() {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse buildPartial() {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse result = new org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse(this);
        int from_bitField0_ = bitField0_;
        if (pairsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            pairs_ = java.util.Collections.unmodifiableList(pairs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.pairs_ = pairs_;
        } else {
          result.pairs_ = pairsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse) {
          return mergeFrom((org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse other) {
        if (other == org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance()) return this;
        if (pairsBuilder_ == null) {
          if (!other.pairs_.isEmpty()) {
            if (pairs_.isEmpty()) {
              pairs_ = other.pairs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePairsIsMutable();
              pairs_.addAll(other.pairs_);
            }
            onChanged();
          }
        } else {
          if (!other.pairs_.isEmpty()) {
            if (pairsBuilder_.isEmpty()) {
              pairsBuilder_.dispose();
              pairsBuilder_ = null;
              pairs_ = other.pairs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pairsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPairsFieldBuilder() : null;
            } else {
              pairsBuilder_.addAllMessages(other.pairs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair> pairs_ =
        java.util.Collections.emptyList();
      private void ensurePairsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          pairs_ = new java.util.ArrayList<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair>(pairs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.Builder, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.PairOrBuilder> pairsBuilder_;

      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public java.util.List<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair> getPairsList() {
        if (pairsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pairs_);
        } else {
          return pairsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public int getPairsCount() {
        if (pairsBuilder_ == null) {
          return pairs_.size();
        } else {
          return pairsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair getPairs(int index) {
        if (pairsBuilder_ == null) {
          return pairs_.get(index);
        } else {
          return pairsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public Builder setPairs(
          int index, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair value) {
        if (pairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePairsIsMutable();
          pairs_.set(index, value);
          onChanged();
        } else {
          pairsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public Builder setPairs(
          int index, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.Builder builderForValue) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          pairs_.set(index, builderForValue.build());
          onChanged();
        } else {
          pairsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public Builder addPairs(org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair value) {
        if (pairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePairsIsMutable();
          pairs_.add(value);
          onChanged();
        } else {
          pairsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public Builder addPairs(
          int index, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair value) {
        if (pairsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePairsIsMutable();
          pairs_.add(index, value);
          onChanged();
        } else {
          pairsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public Builder addPairs(
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.Builder builderForValue) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          pairs_.add(builderForValue.build());
          onChanged();
        } else {
          pairsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public Builder addPairs(
          int index, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.Builder builderForValue) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          pairs_.add(index, builderForValue.build());
          onChanged();
        } else {
          pairsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public Builder addAllPairs(
          java.lang.Iterable<? extends org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair> values) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pairs_);
          onChanged();
        } else {
          pairsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public Builder clearPairs() {
        if (pairsBuilder_ == null) {
          pairs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pairsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public Builder removePairs(int index) {
        if (pairsBuilder_ == null) {
          ensurePairsIsMutable();
          pairs_.remove(index);
          onChanged();
        } else {
          pairsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.Builder getPairsBuilder(
          int index) {
        return getPairsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.PairOrBuilder getPairsOrBuilder(
          int index) {
        if (pairsBuilder_ == null) {
          return pairs_.get(index);  } else {
          return pairsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public java.util.List<? extends org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.PairOrBuilder> 
           getPairsOrBuilderList() {
        if (pairsBuilder_ != null) {
          return pairsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pairs_);
        }
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.Builder addPairsBuilder() {
        return getPairsFieldBuilder().addBuilder(
            org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.getDefaultInstance());
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.Builder addPairsBuilder(
          int index) {
        return getPairsFieldBuilder().addBuilder(
            index, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.getDefaultInstance());
      }
      /**
       * <code>repeated .Pair pairs = 1;</code>
       */
      public java.util.List<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.Builder> 
           getPairsBuilderList() {
        return getPairsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.Builder, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.PairOrBuilder> 
          getPairsFieldBuilder() {
        if (pairsBuilder_ == null) {
          pairsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.Builder, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.PairOrBuilder>(
                  pairs_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          pairs_ = null;
        }
        return pairsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DensityResponse)
    }

    static {
      defaultInstance = new DensityResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DensityResponse)
  }

  public interface PairOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Pair)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>optional string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional double value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>optional double value = 2;</code>
     */
    double getValue();
  }
  /**
   * Protobuf type {@code Pair}
   */
  public static final class Pair extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Pair)
      PairOrBuilder {
    // Use Pair.newBuilder() to construct.
    private Pair(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Pair(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Pair defaultInstance;
    public static Pair getDefaultInstance() {
      return defaultInstance;
    }

    public Pair getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Pair(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              value_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_Pair_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_Pair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.class, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.Builder.class);
    }

    public static com.google.protobuf.Parser<Pair> PARSER =
        new com.google.protobuf.AbstractParser<Pair>() {
      public Pair parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pair(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Pair> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>optional string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private double value_;
    /**
     * <code>optional double value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double value = 2;</code>
     */
    public double getValue() {
      return value_;
    }

    private void initFields() {
      key_ = "";
      value_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair)) {
        return super.equals(obj);
      }
      org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair other = (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair) obj;

      boolean result = true;
      result = result && (hasKey() == other.hasKey());
      if (hasKey()) {
        result = result && getKey()
            .equals(other.getKey());
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getValue())
            == java.lang.Double.doubleToLongBits(
                other.getValue()));
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getValue()));
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Pair}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Pair)
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.PairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_Pair_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_Pair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.class, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.Builder.class);
      }

      // Construct using org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_Pair_descriptor;
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair getDefaultInstanceForType() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.getDefaultInstance();
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair build() {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair buildPartial() {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair result = new org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair) {
          return mergeFrom((org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair other) {
        if (other == org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.Pair) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <code>optional double value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double value = 2;</code>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>optional double value = 2;</code>
       */
      public Builder setValue(double value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Pair)
    }

    static {
      defaultInstance = new Pair(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Pair)
  }

  /**
   * Protobuf service {@code KryoLazyDensityService}
   */
  public static abstract class KryoLazyDensityService
      implements com.google.protobuf.Service {
    protected KryoLazyDensityService() {}

    public interface Interface {
      /**
       * <code>rpc getDensity(.DensityRequest) returns (.DensityResponse);</code>
       */
      public abstract void getDensity(
          com.google.protobuf.RpcController controller,
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest request,
          com.google.protobuf.RpcCallback<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new KryoLazyDensityService() {
        @java.lang.Override
        public  void getDensity(
            com.google.protobuf.RpcController controller,
            org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest request,
            com.google.protobuf.RpcCallback<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse> done) {
          impl.getDensity(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getDensity(controller, (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getDensity(.DensityRequest) returns (.DensityResponse);</code>
     */
    public abstract void getDensity(
        com.google.protobuf.RpcController controller,
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest request,
        com.google.protobuf.RpcCallback<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getDensity(controller, (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest)request,
            com.google.protobuf.RpcUtil.<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.KryoLazyDensityService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getDensity(
          com.google.protobuf.RpcController controller,
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest request,
          com.google.protobuf.RpcCallback<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.class,
            org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse getDensity(
          com.google.protobuf.RpcController controller,
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse getDensity(
          com.google.protobuf.RpcController controller,
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:KryoLazyDensityService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DensityRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DensityRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DensityResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DensityResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pair_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Pair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#KryoLazyDensityProtoGenerator.proto\"$\n" +
      "\016DensityRequest\022\022\n\nbyteFilter\030\001 \002(\014\"\'\n\017D" +
      "ensityResponse\022\024\n\005pairs\030\001 \003(\0132\005.Pair\"\"\n\004" +
      "Pair\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\0012I\n\026Kryo" +
      "LazyDensityService\022/\n\ngetDensity\022\017.Densi" +
      "tyRequest\032\020.DensityResponseBD\n$org.locat" +
      "iontech.geomesa.hbase.protoB\024KryoLazyDen" +
      "sityProtoH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DensityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DensityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DensityRequest_descriptor,
        new java.lang.String[] { "ByteFilter", });
    internal_static_DensityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DensityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DensityResponse_descriptor,
        new java.lang.String[] { "Pairs", });
    internal_static_Pair_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Pair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Pair_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
