/***********************************************************************
 * Copyright (c) 2013-2017 Commonwealth Computer Research, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution and is available at
 * http://www.opensource.org/licenses/apache2.0.php.
 ***********************************************************************/

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KryoLazyDensityProtoGenerator.proto

package org.locationtech.geomesa.hbase.proto;

public final class KryoLazyDensityProto {
  private KryoLazyDensityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DensityRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DensityRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes options = 1;</code>
     */
    boolean hasOptions();
    /**
     * <code>required bytes options = 1;</code>
     */
    com.google.protobuf.ByteString getOptions();
  }
  /**
   * Protobuf type {@code DensityRequest}
   */
  public static final class DensityRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DensityRequest)
      DensityRequestOrBuilder {
    // Use DensityRequest.newBuilder() to construct.
    private DensityRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DensityRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DensityRequest defaultInstance;
    public static DensityRequest getDefaultInstance() {
      return defaultInstance;
    }

    public DensityRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DensityRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              options_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.class, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<DensityRequest> PARSER =
        new com.google.protobuf.AbstractParser<DensityRequest>() {
      public DensityRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DensityRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DensityRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int OPTIONS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString options_;
    /**
     * <code>required bytes options = 1;</code>
     */
    public boolean hasOptions() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes options = 1;</code>
     */
    public com.google.protobuf.ByteString getOptions() {
      return options_;
    }

    private void initFields() {
      options_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOptions()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, options_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, options_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest)) {
        return super.equals(obj);
      }
      org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest other = (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest) obj;

      boolean result = true;
      result = result && (hasOptions() == other.hasOptions());
      if (hasOptions()) {
        result = result && getOptions()
            .equals(other.getOptions());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasOptions()) {
        hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getOptions().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DensityRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DensityRequest)
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.class, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.Builder.class);
      }

      // Construct using org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        options_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityRequest_descriptor;
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest getDefaultInstanceForType() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.getDefaultInstance();
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest build() {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest buildPartial() {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest result = new org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.options_ = options_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest) {
          return mergeFrom((org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest other) {
        if (other == org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.getDefaultInstance()) return this;
        if (other.hasOptions()) {
          setOptions(other.getOptions());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOptions()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString options_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes options = 1;</code>
       */
      public boolean hasOptions() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes options = 1;</code>
       */
      public com.google.protobuf.ByteString getOptions() {
        return options_;
      }
      /**
       * <code>required bytes options = 1;</code>
       */
      public Builder setOptions(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        options_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes options = 1;</code>
       */
      public Builder clearOptions() {
        bitField0_ = (bitField0_ & ~0x00000001);
        options_ = getDefaultInstance().getOptions();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DensityRequest)
    }

    static {
      defaultInstance = new DensityRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DensityRequest)
  }

  public interface DensityResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DensityResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes sf = 1;</code>
     */
    boolean hasSf();
    /**
     * <code>required bytes sf = 1;</code>
     */
    com.google.protobuf.ByteString getSf();
  }
  /**
   * Protobuf type {@code DensityResponse}
   */
  public static final class DensityResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DensityResponse)
      DensityResponseOrBuilder {
    // Use DensityResponse.newBuilder() to construct.
    private DensityResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DensityResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DensityResponse defaultInstance;
    public static DensityResponse getDefaultInstance() {
      return defaultInstance;
    }

    public DensityResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DensityResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sf_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.class, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<DensityResponse> PARSER =
        new com.google.protobuf.AbstractParser<DensityResponse>() {
      public DensityResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DensityResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DensityResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SF_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString sf_;
    /**
     * <code>required bytes sf = 1;</code>
     */
    public boolean hasSf() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes sf = 1;</code>
     */
    public com.google.protobuf.ByteString getSf() {
      return sf_;
    }

    private void initFields() {
      sf_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSf()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, sf_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, sf_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse)) {
        return super.equals(obj);
      }
      org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse other = (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse) obj;

      boolean result = true;
      result = result && (hasSf() == other.hasSf());
      if (hasSf()) {
        result = result && getSf()
            .equals(other.getSf());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSf()) {
        hash = (37 * hash) + SF_FIELD_NUMBER;
        hash = (53 * hash) + getSf().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DensityResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DensityResponse)
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.class, org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.Builder.class);
      }

      // Construct using org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sf_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.internal_static_DensityResponse_descriptor;
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse getDefaultInstanceForType() {
        return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance();
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse build() {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse buildPartial() {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse result = new org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sf_ = sf_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse) {
          return mergeFrom((org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse other) {
        if (other == org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance()) return this;
        if (other.hasSf()) {
          setSf(other.getSf());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSf()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString sf_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes sf = 1;</code>
       */
      public boolean hasSf() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes sf = 1;</code>
       */
      public com.google.protobuf.ByteString getSf() {
        return sf_;
      }
      /**
       * <code>required bytes sf = 1;</code>
       */
      public Builder setSf(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes sf = 1;</code>
       */
      public Builder clearSf() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sf_ = getDefaultInstance().getSf();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DensityResponse)
    }

    static {
      defaultInstance = new DensityResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DensityResponse)
  }

  /**
   * Protobuf service {@code KryoLazyDensityService}
   */
  public static abstract class KryoLazyDensityService
      implements com.google.protobuf.Service {
    protected KryoLazyDensityService() {}

    public interface Interface {
      /**
       * <code>rpc getDensity(.DensityRequest) returns (.DensityResponse);</code>
       */
      public abstract void getDensity(
          com.google.protobuf.RpcController controller,
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest request,
          com.google.protobuf.RpcCallback<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new KryoLazyDensityService() {
        @java.lang.Override
        public  void getDensity(
            com.google.protobuf.RpcController controller,
            org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest request,
            com.google.protobuf.RpcCallback<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse> done) {
          impl.getDensity(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getDensity(controller, (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getDensity(.DensityRequest) returns (.DensityResponse);</code>
     */
    public abstract void getDensity(
        com.google.protobuf.RpcController controller,
        org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest request,
        com.google.protobuf.RpcCallback<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getDensity(controller, (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest)request,
            com.google.protobuf.RpcUtil.<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.KryoLazyDensityService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getDensity(
          com.google.protobuf.RpcController controller,
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest request,
          com.google.protobuf.RpcCallback<org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.class,
            org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse getDensity(
          com.google.protobuf.RpcController controller,
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse getDensity(
          com.google.protobuf.RpcController controller,
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.locationtech.geomesa.hbase.proto.KryoLazyDensityProto.DensityResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:KryoLazyDensityService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DensityRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DensityRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DensityResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DensityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#KryoLazyDensityProtoGenerator.proto\"!\n" +
      "\016DensityRequest\022\017\n\007options\030\001 \002(\014\"\035\n\017Dens" +
      "ityResponse\022\n\n\002sf\030\001 \002(\0142I\n\026KryoLazyDensi" +
      "tyService\022/\n\ngetDensity\022\017.DensityRequest" +
      "\032\020.DensityResponseBD\n$org.locationtech.g" +
      "eomesa.hbase.protoB\024KryoLazyDensityProto" +
      "H\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DensityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DensityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DensityRequest_descriptor,
        new java.lang.String[] { "Options", });
    internal_static_DensityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DensityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DensityResponse_descriptor,
        new java.lang.String[] { "Sf", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
