s3-endpoint = ${?S3_ENDPOINT_URL}
// region = <can be set here, but usually is configured via the aws sdk using AWS_REGION or ~/.aws/config>
// access-key-id = <can be set here, but usually is configured via the aws sdk using AWS_ACCESS_KEY_ID, or ~/.aws/credentials>
// secret-access-key = <can be set here, but usually is configured via the aws sdk using AWS_SECRET_ACCESS_KEY, or ~/.aws/credentials>
path-style-access = false
path-style-access = ${?S3_PATH_STYLE_ACCESS}
