"fs.s3.endpoint" = ${?FS_S3_ENDPOINT}
// "fs.s3.region" = <can be set here, but usually is configured via the aws sdk using AWS_REGION or ~/.aws/config>
// "fs.s3.access-key-id" = <can be set here, but usually is configured via the aws sdk using AWS_ACCESS_KEY_ID, or ~/.aws/credentials>
// "fs.s3.secret-access-key" = <can be set here, but usually is configured via the aws sdk using AWS_SECRET_ACCESS_KEY, or ~/.aws/credentials>
"fs.s3.force-path-style" = false
"fs.s3.force-path-style" = ${?FS_S3_FORCE_PATH_STYLE}
"fs.s3.write-buffering" = "disk" // or memory
"fs.s3.write-buffering" = ${?FS_S3_WRITE_BUFFERING} // or memory
"fs.s3.write-buffer-dir" = ${java.io.tmpdir}/s3/
"fs.s3.write-buffer-dir" = ${?FS_S3_WRITE_BUFFER_DIR}
"fs.s3.write-buffer-in-bytes" = "64MB"
"fs.s3.write-buffer-in-bytes" = ${?FS_S3_WRITE_BUFFER_IN_BYTES}
// crt client configurations - see aws documentation for details
"fs.s3.num-retries" = ${?FS_S3_NUM_RETRIES}
"fs.s3.target-throughput-in-gbps" = ${?FS_S3_TARGET_THROUGHPUT_IN_GBPS}
"fs.s3.minimum-part-size-in-bytes" = ${?FS_S3_MINIMUM_PART_SIZE_IN_BYTES}
"fs.s3.max-concurrency" = 600
"fs.s3.max-concurrency" = ${?FS_S3_MAX_CONCURRENCY}
"fs.s3.connection-timeout" = ${?FS_S3_CONNECTION_TIMEOUT}
"fs.s3.max-native-memory-limit-in-bytes" = ${?FS_S3_MAX_NATIVE_MEMORY_LIMIT_IN_BYTES}
"fs.s3.request-checksum-calculation" = ${?FS_S3_REQUEST_CHECKSUM_CALCULATION} // <WHEN_SUPPORTED or WHEN_REQUIRED>
"fs.s3.response-checksum-validation" = ${?FS_S3_RESPONSE_CHECKSUM_VALIDATION} // <WHEN_SUPPORTED or WHEN_REQUIRED>
"fs.s3.initial-read-buffer-size-in-bytes" = ${?FS_S3_INITIAL_READ_BUFFER_SIZE_IN_BYTES}
"fs.s3.accelerate" = ${?FS_S3_ACCELERATE}
"fs.s3.threshold-in-bytes" = ${?FS_S3_THRESHOLD_IN_BYTES}
