s3-endpoint = ${?S3_ENDPOINT_URL}
// region = <can be set here, but usually is configured via the aws sdk using AWS_REGION or ~/.aws/config>
// access-key-id = <can be set here, but usually is configured via the aws sdk using AWS_ACCESS_KEY_ID, or ~/.aws/credentials>
// secret-access-key = <can be set here, but usually is configured via the aws sdk using AWS_SECRET_ACCESS_KEY, or ~/.aws/credentials>
path-style-access = false
path-style-access = ${?S3_PATH_STYLE_ACCESS}
write-buffer-in-bytes = 1048576 // 1Mib
write-buffer-in-bytes = ${?S3_WRITE_BUFFER_IN_BYTES}
// crt client configurations - see aws documentation for details
num-retries = ${?S3_NUM_RETRIES}
target-throughput-in-gbps = ${?S3_TARGET_THROUGHPUT_IN_GBPS}
minimum-part-size-in-bytes = ${?S3_MINIMUM_PART_SIZE_IN_BYTES}
max-concurrency = ${?S3_MAX_CONCURRENCY}
connection-timeout = ${?S3_CONNECTION_TIMEOUT}
max-native-memory-limit-in-bytes = ${?S3_MAX_NATIVE_MEMORY_LIMIT_IN_BYTES}
request-checksum-calculation = ${?S3_REQUEST_CHECKSUM_CALCULATION} // <WHEN_SUPPORTED or WHEN_REQUIRED>
response-checksum-validation = ${?S3_RESPONSE_CHECKSUM_VALIDATION} // <WHEN_SUPPORTED or WHEN_REQUIRED>
initial-read-buffer-size-in-bytes = ${?S3_INITIAL_READ_BUFFER_SIZE_IN_BYTES}
accelerate = ${?S3_ACCELERATE}
threshold-in-bytes = ${?S3_THRESHOLD_IN_BYTES}
