coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080
task.concurrency=32
task.max-writer-count=8
query.max-memory=4GB
query.max-memory-per-node=4GB
