name: build-javadocs

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
    tags:
      - '**'
  pull_request:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

env:
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dlicense.skip=true --batch-mode

jobs:
  build-javadocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
        with:
          key: ${{ hashFiles('**/pom.xml') }}-javadocs
          path: ~/.m2/repository/
      - name: Build scaladocs
        run: mvn clean generate-sources scala:doc-jar $MAVEN_CLI_OPTS
      - name: Build javadocs
        run: mvn clean generate-sources javadoc:jar $MAVEN_CLI_OPTS -pl :geomesa-arrow-jts
