name: build

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
    tags:
      - '**'
  pull_request:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  build-scala:
    strategy:
      matrix:
        version: [ "2.12", "2.13" ]
    uses: ./.github/workflows/build-and-test.yml
    with:
      scala-version: ${{ matrix.version }}
