name: weekly-dash-check

on:
  workflow_dispatch:
  schedule:
    - cron: '20 21 * * 0'

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

env:
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false --batch-mode

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ "2.12", "2.13" ]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: ${{ hashFiles('**/pom.xml') }}-dash-scheduled-${{ matrix.version }}
          path: |
            ~/.m2/repository/
            build/zinc-0.3.15/
      - name: Set Scala version
        run: ./build/scripts/change-scala-version.sh ${{ matrix.version }}
      - name: Build with Maven
        run: ./build/mvn clean install $MAVEN_CLI_OPTS -DskipTests -T4
      - name: Collect artifacts
        run: |
          mv ~/.m2/repository/org/locationtech/geomesa m2-geomesa
          tar -czf classes.tgz $(find . -path '*/target/classes' -o -path '*/target/test-classes' -type d | tr '\n' ' ')
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: classes-and-jars-${{ matrix.version }}
          retention-days: 1
          path: |
            m2-geomesa
            classes.tgz
      - name: Remove geomesa artifacts
        if: success() || failure()
        run: rm -rf ~/.m2/repository/org/locationtech/geomesa
  dash:
    needs: compile
    strategy:
      fail-fast: false
      matrix:
        version: [ "2.12", "2.13" ]
    uses: ./.github/workflows/dash.yml
    with:
      scala-version: ${{ matrix.version }}
