name: weekly-dash-check

on:
  workflow_dispatch:
  schedule:
    - cron: '20 21 * * 0'

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

env:
  JAVA_VERSION: 17
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false --batch-mode

jobs:
  dash:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ "2.12", "2.13" ]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: "${{ env.JAVA_VERSION }}"
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: ${{ hashFiles('**/pom.xml') }}-dash-scheduled-${{ matrix.version }}
          path: ~/.m2/repository/
      - name: Set Scala version
        run: ./build/scripts/change-scala-version.sh ${{ matrix.version }}
      - name: Build with Maven
        run: mvn clean install -Dmaven.assembly.skip=true -Dmaven.source.skip -T4 $MAVEN_CLI_OPTS
      - name: License check
        run: mvn org.eclipse.dash:license-tool-plugin:license-check -Ddash.fail=true -Ddash.projectId=locationtech.geomesa -DexcludeGroupIds=org.locationtech.geomesa $MAVEN_CLI_OPTS
      - name: Show license
        if: success() || failure()
        run: cat target/dash/summary
      - name: Remove geomesa artifacts
        if: success() || failure()
        run: rm -rf ~/.m2/repository/org/locationtech/geomesa
