name: dash-test

on:
  pull_request:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

env:
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dlicense.skip=true --batch-mode

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2 # needed for checking for pom changes
      - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Check for pom.xml changes
        id: pom_changes
        run: |
          if [[ "${{ github.event_name }}" != "pull_request" ]]; then
            echo "Always running dash for direct push (main, long-term branches, and tags)"
            pomChanged="true"
          else
            pomChanged="false"
            # get the changed files: https://stackoverflow.com/a/74268200/7809538
            changedFiles=()
            commitShas='${{ join(github.event.commits.*.id, ' ') }}'
            for filename in $(git diff --name-only HEAD^1 HEAD); do
              changedFiles+=("$filename")
              if [[ $filename =~ .*pom.xml ]]; then
                pomChanged="true"
              fi
            done
            echo "Changed files:"
            for file in "${changedFiles[@]}"; do
             echo "  $file"
            done 
          fi
          echo "pom_changed=$pomChanged" >> "$GITHUB_OUTPUT"
      - name: License check
        if: steps.pom_changes.outputs.pom_changed == 'true'
        run: echo mvn org.eclipse.dash:license-tool-plugin:license-check $MAVEN_CLI_OPTS -Ddash.fail=true -Ddash.projectId=locationtech.geomesa -DexcludeGroupIds=org.locationtech.geomesa
      - name: Show license
        if: success() || failure()
        run: |
          if [[ -f target/dash/summary ]]; then
            cat target/dash/summary
          else
            echo "No pom changes detected - skipping license check"
          fi
