name: module-unit-tests

on:
  workflow_call:
    inputs:
      scala-version:
        required: false
        type: string
        default: "2.12"
      module-selector:
        required: true
        type: string

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

env:
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dlicense.skip=true --batch-mode
  MAVEN_TEST_OPTS: -Dtest.fork.count=1

jobs:
  module-unit-tests:
    runs-on: ubuntu-latest
    # avoid duplicate jobs on PRs from the main repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Set Scala version
        with:
          scala-version: ${{ inputs.scala-version }}
        run: |
          echo ./build/scripts/change-scala-version.sh ${scala-version}
          ./build/scripts/change-scala-version.sh ${scala-version}
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: classes-and-jars
      - name: Install artifacts
        run: |
          tar -xf classes.tgz
          mkdir -p ~/.m2/repository/org/locationtech/geomesa
          mv m2-geomesa/* ~/.m2/repository/org/locationtech/geomesa/
      - name: Unit tests
        id: test
        continue-on-error: true
        with:
          module-selector: ${{ inputs.module-selector }}
        run: |
          set -o pipefail
          echo mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS ${module-selector}
          mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS ${module-selector} | tee -a test.log
      - name: Unit tests (retry)
        id: test-retry
        if: steps.test.outcome=='failure'
        continue-on-error: true
        run: |
          set -o pipefail
          RESUME_FROM="$(grep --text 'mvn <args> -rf ' test.log | tail -n1 | sed 's/.*-rf/-rf/')"
          mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS $RESUME_FROM ${module-selector} | tee -a test.log
      - name: Unit tests (retry)
        id: test-retry-retry
        if: steps.test-retry.outcome=='failure'
        run: |
          set -o pipefail
          RESUME_FROM="$(grep --text 'mvn <args> -rf ' test.log | tail -n1 | sed 's/.*-rf/-rf/')"
          mvn surefire:test $MAVEN_CLI_OPTS $MAVEN_TEST_OPTS $RESUME_FROM ${module-selector} | tee -a test.log
      - name: Remove geomesa artifacts
        if: success() || failure()
        run: rm -rf ~/.m2/repository/org/locationtech/geomesa
