name: release

on:
  push:
    tags:
      - '**'

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

env:
  JAVA_VERSION: 17
  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false --batch-mode -Dlicense.skip=true
  MAVEN_RELEASE_ARGS: clean deploy -Prelease -DaltDeploymentRepository=local::file:./staging-deploy
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-github-release:
    name: create-github-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Create GitHub release
        run: |
          version="${GITHUB_REF_NAME#geomesa-}"
          gh release create ${GITHUB_REF_NAME} \
            --repo ${GITHUB_REPOSITORY} \
            --title "GeoMesa ${version}" \
            --notes "[Release notes](https://geomesa.atlassian.net/wiki/display/GEOMESA/GeoMesa+${version}+Release+Notes)"\
            --prerelease \
            --verify-tag

  build:
    name: build / ${{ matrix.scala-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: create-github-release
    strategy:
      fail-fast: false
      matrix:
        scala-version: [ "2.12", "2.13" ]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: temurin
          java-version: "${{ env.JAVA_VERSION }}"
      - name: Set Scala version
        run: ./build/scripts/change-scala-version.sh ${{ matrix.scala-version }}
      - name: Build
        id: build
        continue-on-error: true
        run: |
          set -o pipefail
          mvn $MAVEN_RELEASE_ARGS $MAVEN_CLI_OPTS | tee -a build.log
      - name: Build (retry)
        if: steps.build.outcome=='failure'
        run: |
          set -o pipefail
          # retry if the failure was due to transient download errors from maven central
          if grep -q -e 'Could not transfer artifact' -e 'Failed to read artifact descriptor' build.log; then
            RESUME_FROM="$({ grep --text 'mvn <args> -rf ' build.log || test $? = 1; } | tail -n1 | sed 's/.*-rf/-rf/')"
            mvn $MAVEN_RELEASE_ARGS $MAVEN_CLI_OPTS $RESUME_FROM | tee -a build.log
          else
            exit 1
          fi
      - name: Upload release artifacts
        run: |
          echo "Copying release artifacts"
          tar -czf staging-deploy_${{ matrix.scala-version }}.tgz ./staging-deploy/
          gh release upload ${GITHUB_REF_NAME} \
              --repo ${GITHUB_REPOSITORY} \
              staging-deploy_${{ matrix.scala-version }}.tgz
          while IFS= read -r -d '' file; do
            pushd "$(dirname "$file")" >/dev/null
            sha256sum "$(basename "$file")" > "$(basename "$file").sha256"
            popd >/dev/null
            # GitHub CLI does not respect their own rate limits: https://github.com/cli/cli/issues/9586
            sleep 1
            gh release upload ${GITHUB_REF_NAME} \
              --repo ${GITHUB_REPOSITORY} \
              $file
            sleep 1
            gh release upload ${GITHUB_REF_NAME} \
              --repo ${GITHUB_REPOSITORY} \
              ${file}.sha256
          done < <(find geomesa-* -name '*-bin.tar.gz' -print0)
